version: '2'
services:
    web:
        image: "nginx"
        volumes:
            - "./html/build:/usr/share/nginx/html:ro"
        ports:
            - "4000:80"
        restart: "always"
    api:
        build: .
        links:
            - db
        ports:
            - "3000:3000"
        volumes:
            - "./api:/usr/src/app"
        restart: "always"
    db:
        image: "mariadb"
        volumes:
            - "./sql/data.sql:/docker-entrypoint-initdb.d/data.sql:ro"
            - "./.db:/var/lib/mysql"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        restart: "always"
